"""migrating new data

Revision ID: 0650e388001a
Revises: 041a17bd8e6a
Create Date: 2020-09-20 11:47:29.785346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0650e388001a'
down_revision = '041a17bd8e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('my_pitch', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'my_pitch')
    # ### end Alembic commands ###
