"""migrating new data

Revision ID: 93fde8221b97
Revises: ea80f49cd944
Create Date: 2020-09-20 15:38:47.855270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fde8221b97'
down_revision = 'ea80f49cd944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'posted')
    # ### end Alembic commands ###
