"""migrating new data

Revision ID: a9d7e6a9975e
Revises: 93fde8221b97
Create Date: 2020-09-20 17:27:53.740302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d7e6a9975e'
down_revision = '93fde8221b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'posted')
    # ### end Alembic commands ###
