"""migrating new data

Revision ID: d2632f53d912
Revises: 18c8302bcab8
Create Date: 2020-09-22 14:07:15.787783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2632f53d912'
down_revision = '18c8302bcab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'my_pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('my_pitch', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
